"""Event types for agent communication."""

from enum import Enum


class EventType(str, Enum):
    """Types of events that flow through the outbox."""

    # Ingestion events
    ITEM_UPSERTED = "ITEM_UPSERTED"
    ITEM_DELETED = "ITEM_DELETED"
    PASSAGES_CREATED = "PASSAGES_CREATED"

    # Indexing events
    VECTORS_CREATED = "VECTORS_CREATED"
    TEXT_INDEXED = "TEXT_INDEXED"
    GRAPH_INDEXED = "GRAPH_INDEXED"

    # Entity events
    ENTITIES_EXTRACTED = "ENTITIES_EXTRACTED"
    ENTITY_MERGED = "ENTITY_MERGED"
    ENTITY_PAGE_DIRTY = "ENTITY_PAGE_DIRTY"

    # Claim events (Knowledge Kernel)
    CLAIM_PROPOSED = "CLAIM_PROPOSED"
    CLAIM_ACCEPTED = "CLAIM_ACCEPTED"
    CLAIM_REJECTED = "CLAIM_REJECTED"
    CLAIM_CONFLICT_DETECTED = "CLAIM_CONFLICT_DETECTED"
    CLAIM_MERGED = "CLAIM_MERGED"

    # Artifact events
    ARTIFACT_CREATED = "ARTIFACT_CREATED"
    ARTIFACT_UPDATED = "ARTIFACT_UPDATED"

    # Workflow events
    WORKFLOW_STARTED = "WORKFLOW_STARTED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"

    # Adaptive Cognitive Plane (ACP) events
    STRATEGY_CREATED = "STRATEGY_CREATED"
    STRATEGY_APPLIED = "STRATEGY_APPLIED"
    STRATEGY_DEPRECATED = "STRATEGY_DEPRECATED"
    STRATEGY_EVALUATED = "STRATEGY_EVALUATED"
    OUTCOME_RECORDED = "OUTCOME_RECORDED"
    PROPOSAL_CREATED = "PROPOSAL_CREATED"
    PROPOSAL_APPROVED = "PROPOSAL_APPROVED"
    PROPOSAL_REJECTED = "PROPOSAL_REJECTED"
    RESTRUCTURE_STARTED = "RESTRUCTURE_STARTED"
    RESTRUCTURE_COMPLETED = "RESTRUCTURE_COMPLETED"
    RESTRUCTURE_ROLLED_BACK = "RESTRUCTURE_ROLLED_BACK"

    # Legacy planning events (deprecated, use Knowledge Kernel)
    TASK_REQUESTED = "TASK_REQUESTED"
    PLAN_CREATED = "PLAN_CREATED"
    PLAN_STEP_COMPLETED = "PLAN_STEP_COMPLETED"
    AGENT_DISPATCHED = "AGENT_DISPATCHED"
